### ISSUE TITLE
Why npx?

### ISSUE THREAD

**Issue by abmmhasan** [dotenv-org/phpdotenv-vault#12]
Writing a library for PHP but requiring Node.Js (The **NPX**)? Why not using PHP's in built system?

**Comment by motdotla** [comment]
because the cli library is different than the PHP lib. The PHP lib does decryption and injection of .env.vault only. the cli library - which is built with node and distributed via npx - contains all the api coordination with vault.dotenv.org.

**Comment by motdotla** [comment]
that said, if using PHP you might also prefer [`dotenvx`](https://github.com/dotenvx/dotenvx)
