### ISSUE TITLE
NOT_FOUND_DOTENV_ENVIRONMENT in version 0.1.2

### ISSUE THREAD

**Issue by SchoppAx** [dotenv-org/phpdotenv-vault#2]
Hi,

after updating to package version 0.1.2, phpdotenv-vault throws: 
`NOT_FOUND_DOTENV_ENVIRONMENT: Cannot locate environment DOTENV_VAULT_DEVELOPMENT in your .env.vault file. Run 'npx dotenv-vault build' to include it.`

PHP: 8.2
phpdotenv-vault: 0.1.2

In my opinion the problem is, the last change [Use getenv instead of](https://github.com/dotenv-org/phpdotenv-vault/commit/61dbb12f3d360027092e36b6e42a388d1bae3cb4#diff-fd8d756b4993a15beae36bd9ce9a8e48c0f0f8d86daa641519a6235ce6d91991L81-R81)

Why?
We load our .env with the following code:
```php
$dotenv = DotenvVault::createImmutable(__DIR__, '.env.vault');
$dotenv->load();
```
The function `createImmutable` calls `RepositoryBuilder::createWithDefaultAdapters()`. The used default adapters are `ServerConstAdapter` and `EnvConstAdapter` ([ref vlucas/phpdotenv/src/Repository/RepositoryBuilder.php](https://github.com/vlucas/phpdotenv/blob/1a7ea2afc49c3ee6d87061f5a233e3a035d0eae7/src/Repository/RepositoryBuilder.php#L25-L28)).
These adapters write our environment variables to `$_SERVER` and `$_ENV`. So with these adapers we can't access our variables via `getenv`. The needed `PutenvAdapter` is only added inside `createUnsafeImmutable`.

How to deal with it?

**Comment by motdotla** [comment]
This is fixed in the latest. Sorry for the delay on this. This library was largely broken. :(

It is all fixed up now. 🎉

https://github.com/dotenv-org/phpdotenv-vault/tree/v0.2.4
