### ISSUE TITLE
Load fallback .env prints first entry

### ISSUE THREAD

**Issue by SchoppAx** [dotenv-org/phpdotenv-vault#3]
Hi,

if there is no DOTENV_KEY phpdotenv-vault fallback to the unencrypted .env file.
In this case there is a `var_dump` on first .env entry ([ref](https://github.com/dotenv-org/phpdotenv-vault/blob/61dbb12f3d360027092e36b6e42a388d1bae3cb4/src/DotenvVault.php#L54-L55))
```php
var_dump($entries[0]->getName());
var_dump($entries[0]->getValue());
```

If there should be an output, it would be better to add a notice or warning so that it can be ignored by `error_reporting`.
```php
trigger_error('Fallback to unencrypted .env', E_USER_NOTICE);
```

**Comment by motdotla** [comment]
Fixed. https://github.com/dotenv-org/phpdotenv-vault/blob/master/CHANGELOG.md#013

thank you for your patience. PHP is getting some love over this weekend. A lot of php users of .env.vault now and this library needs a LOT of work.

Loving PHP by the way! Bringing me back to the good old days.

**Comment by motdotla** [comment]
We won't do the warning though. We'll follow the same approach as the node dotenv library:

1. Default fallback to `.env`
2. If `DOTENV_KEY` is set then look for `.env.vault` file.
3. If .env.vault file is then not found warn user
4. If .env.vault file is found then show log message that envs are being loaded from encrypted .env.vault file
