### ISSUE TITLE
PHPStan: Class DotenvVault\\DotEnvVault referenced with incorrect case: DotenvVault\\DotenvVault

### ISSUE THREAD

**Issue by SchoppAx** [dotenv-org/phpdotenv-vault#6]
Hi,

the class name is written in CamelCase so the current readme example:
https://github.com/dotenv-org/phpdotenv-vault/blob/61dbb12f3d360027092e36b6e42a388d1bae3cb4/README.md?plain=1#L37-L41

Should be look like:
```php
use DotenvVault\DotEnvVault; 
require 'vendor/autoload.php'; 
  
$dotenv = DotEnvVault::createImmutable(__DIR__, '.env.vault'); 
$dotenv->load(); # take environment variables from .env.vault 
```

**Comment by motdotla** [comment]
This is fixed in `v0.2.x`. Thank you for catching this. This library is getting love and documentation this weekend.
